# Generated by Django 2.2.4 on 2019-09-03 04:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('poryphone', '0002_auto_20190903_0015'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pokemon',
            name='weakness',
        ),
        migrations.AddField(
            model_name='pokemon',
            name='weakness',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pokemon_weakness', to='poryphone.Type'),
        ),
    ]
