# Generated by Django 2.2.4 on 2019-09-03 22:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('poryphone', '0003_auto_20190903_0026'),
    ]

    operations = [
        migrations.AddField(
            model_name='trainer',
            name='base_potential',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='trainer',
            name='recruit_method',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
