# Generated by Django 2.2.4 on 2019-09-04 00:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('poryphone', '0004_auto_20190903_1815'),
    ]

    operations = [
        migrations.AddField(
            model_name='pokemon',
            name='moves',
            field=models.ManyToManyField(blank=True, related_name='pokemon_move', to='poryphone.Move'),
        ),
    ]
