# Generated by Django 2.2.4 on 2019-09-04 02:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('poryphone', '0005_pokemon_moves'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='family',
            name='evo_ids',
        ),
        migrations.RemoveField(
            model_name='move',
            name='pp',
        ),
        migrations.AddField(
            model_name='move',
            name='is_energy',
            field=models.BooleanField(default=True),
        ),
    ]
