# Generated by Django 2.2.4 on 2019-09-04 02:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('poryphone', '0006_auto_20190903_2226'),
    ]

    operations = [
        migrations.AlterField(
            model_name='move',
            name='type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='poryphone.Type'),
        ),
    ]
