# Generated by Django 2.2.4 on 2019-09-04 02:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('poryphone', '0007_auto_20190903_2229'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('img_path', models.CharField(max_length=255)),
            ],
        ),
    ]
