# Generated by Django 2.2.4 on 2019-09-04 02:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('poryphone', '0008_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='img_path',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='move',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='poryphone.Category'),
        ),
    ]
