# Generated by Django 2.2.4 on 2019-09-04 16:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('poryphone', '0009_auto_20190903_2237'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='family',
            name='is_parent',
        ),
        migrations.AddField(
            model_name='family',
            name='name',
            field=models.CharField(default='Unown', max_length=255),
        ),
        migrations.AddField(
            model_name='pokemon',
            name='evo_stage',
            field=models.IntegerField(default=1),
        ),
        migrations.RemoveField(
            model_name='family',
            name='pokemon',
        ),
        migrations.AddField(
            model_name='family',
            name='pokemon',
            field=models.ManyToManyField(to='poryphone.Pokemon'),
        ),
    ]
