# Generated by Django 2.2.4 on 2019-09-04 16:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('poryphone', '0010_auto_20190904_1201'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='pokemon',
            options={'ordering': ['id']},
        ),
    ]
