# Generated by Django 2.2.4 on 2019-11-02 14:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('poryphone', '0012_auto_20190905_0120'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='family',
            name='pokemon',
        ),
        migrations.AddField(
            model_name='pokemon',
            name='family',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='pokemons', to='poryphone.Family'),
        ),
    ]
