# Generated by Django 2.2.4 on 2019-11-02 14:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('poryphone', '0013_auto_20191102_1023'),
    ]

    operations = [
        migrations.AlterField(
            model_name='family',
            name='name',
            field=models.CharField(blank=True, default='Unown', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='pokemon',
            name='family',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='pokemons', to='poryphone.Family'),
        ),
    ]
