# Generated by Django 2.2.4 on 2019-11-02 14:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('poryphone', '0015_auto_20191102_1039'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pokemon',
            name='moves',
        ),
        migrations.DeleteModel(
            name='Move',
        ),
    ]
