# Generated by Django 2.2.4 on 2019-11-02 14:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('poryphone', '0017_move'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Target',
        ),
    ]
