# Generated by Django 2.2.4 on 2019-11-02 23:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('poryphone', '0021_pokemon_moves'),
    ]

    operations = [
        migrations.CreateModel(
            name='SyncPair',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, default='Unown', max_length=255, null=True)),
                ('moves', models.ManyToManyField(blank=True, null=True, related_name='syncpair_move', to='poryphone.Move')),
            ],
        ),
        migrations.RemoveField(
            model_name='pokemon',
            name='family',
        ),
        migrations.RemoveField(
            model_name='pokemon',
            name='moves',
        ),
        migrations.DeleteModel(
            name='Family',
        ),
        migrations.AddField(
            model_name='pokemon',
            name='syncpair',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='pokemons', to='poryphone.SyncPair'),
        ),
    ]
