# Generated by Django 2.2.4 on 2019-11-03 03:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('poryphone', '0024_auto_20191102_2315'),
    ]

    operations = [
        migrations.CreateModel(
            name='RecruitMethod',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.RemoveField(
            model_name='trainer',
            name='base_potential',
        ),
        migrations.AlterField(
            model_name='trainer',
            name='recruit_method',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='poryphone.RecruitMethod'),
        ),
    ]
