# Generated by Django 2.2.4 on 2019-11-03 23:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('poryphone', '0025_auto_20191102_2359'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='trainer',
            name='recruit_method',
        ),
        migrations.AlterField(
            model_name='syncpair',
            name='role',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='poryphone.Role'),
        ),
        migrations.AlterField(
            model_name='syncpair',
            name='trainer',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='syncpair', to='poryphone.Trainer'),
        ),
    ]
