# Generated by Django 2.2.4 on 2019-11-04 00:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('poryphone', '0026_auto_20191103_1835'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pokemon',
            name='role',
        ),
        migrations.AlterField(
            model_name='pokemon',
            name='syncpair',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='pokemon', to='poryphone.SyncPair'),
        ),
    ]
