# Generated by Django 2.2.4 on 2019-11-04 00:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('poryphone', '0027_auto_20191103_1923'),
    ]

    operations = [
        migrations.AddField(
            model_name='syncpair',
            name='recruit_method',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='poryphone.RecruitMethod'),
        ),
    ]
