# Generated by Django 2.2.4 on 2019-11-04 02:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('poryphone', '0028_syncpair_recruit_method'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pokemon',
            name='syncpair',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pokemon', to='poryphone.SyncPair'),
        ),
    ]
