# Generated by Django 2.2.4 on 2019-11-05 01:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('poryphone', '0029_auto_20191103_2117'),
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('description', models.CharField(blank=True, max_length=255, null=True)),
                ('obtain_method', models.CharField(blank=True, max_length=255, null=True)),
                ('img_path', models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
    ]
