# Generated by Django 2.2.4 on 2019-11-05 04:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('poryphone', '0030_item'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='syncpair',
            name='moves',
        ),
        migrations.AlterField(
            model_name='syncpair',
            name='trainer',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='trainer', to='poryphone.Trainer'),
        ),
        migrations.CreateModel(
            name='SyncPairMove',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('move', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='move', to='poryphone.Move')),
                ('syncpair', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='syncpair', to='poryphone.SyncPair')),
            ],
        ),
    ]
