# Generated by Django 2.2.4 on 2019-11-05 04:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('poryphone', '0032_auto_20191104_2311'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trainer',
            name='name',
            field=models.CharField(max_length=255, unique=True),
        ),
        migrations.AlterUniqueTogether(
            name='syncpair',
            unique_together={('name', 'trainer')},
        ),
        migrations.CreateModel(
            name='SyncPairMoveItem',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('quantity', models.IntegerField(blank=True, null=True)),
                ('item', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='item', to='poryphone.Item')),
                ('syncpairmove', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='spmove', to='poryphone.SyncPairMove')),
            ],
        ),
    ]
