# Generated by Django 2.2.4 on 2019-11-05 04:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('poryphone', '0033_auto_20191104_2351'),
    ]

    operations = [
        migrations.AlterField(
            model_name='syncpairmoveitem',
            name='item',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='item', to='poryphone.Item'),
        ),
    ]
