# Generated by Django 2.2.4 on 2019-11-06 02:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('poryphone', '0036_auto_20191105_2147'),
    ]

    operations = [
        migrations.AlterField(
            model_name='move',
            name='name',
            field=models.CharField(max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='pokemon',
            name='name',
            field=models.CharField(max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='recruitmethod',
            name='name',
            field=models.CharField(max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='role',
            name='name',
            field=models.CharField(max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='syncpair',
            name='name',
            field=models.CharField(blank=True, default='Unown', max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='syncpairmove',
            name='unlock_requirements',
            field=models.ManyToManyField(blank=True, related_name='items', to='poryphone.ItemQuantity'),
        ),
        migrations.AlterField(
            model_name='target',
            name='name',
            field=models.CharField(max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='type',
            name='name',
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
