# Generated by Django 2.2.4 on 2019-11-06 02:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('poryphone', '0037_auto_20191105_2150'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='type',
            name='description',
        ),
        migrations.AddField(
            model_name='pokemon',
            name='description',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
