# Generated by Django 2.2.4 on 2019-11-10 23:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('poryphone', '0038_auto_20191105_2150'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='pokemon',
            options={'ordering': ['name']},
        ),
        migrations.AlterModelOptions(
            name='syncpair',
            options={'ordering': ['name']},
        ),
    ]
