# Generated by Django 2.2.4 on 2019-11-11 00:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('poryphone', '0040_auto_20191110_1923'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='trainer',
            options={'ordering': ['name']},
        ),
    ]
