# Generated by Django 2.2.4 on 2019-11-11 04:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('poryphone', '0041_auto_20191110_1923'),
    ]

    operations = [
        migrations.AlterField(
            model_name='syncpair',
            name='trainer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='trainer', to='poryphone.Trainer'),
        ),
    ]
