# Generated by Django 2.2.4 on 2020-01-10 17:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('poryphone', '0042_auto_20191110_2331'),
    ]

    operations = [
        migrations.RenameField(
            model_name='move',
            old_name='cost',
            new_name='energy_cost',
        ),
        migrations.RemoveField(
            model_name='move',
            name='is_energy',
        ),
        migrations.AddField(
            model_name='move',
            name='num_uses',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
