# Generated by Django 2.2.4 on 2020-02-07 14:05

import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('poryphone', '0043_auto_20200110_1241'),
    ]

    operations = [
        migrations.CreateModel(
            name='Passive',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255, unique=True)),
                ('description', models.CharField(blank=True, max_length=255, null=True, unique=True)),
            ],
        ),
        migrations.AlterField(
            model_name='itemquantity',
            name='item',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='iq_item', to='poryphone.Item'),
        ),
        migrations.AlterField(
            model_name='syncpairmove',
            name='move',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='spm_move', to='poryphone.Move'),
        ),
        migrations.AlterField(
            model_name='syncpairmove',
            name='syncpair',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='spm_syncpair', to='poryphone.SyncPair'),
        ),
        migrations.AlterField(
            model_name='syncpairmove',
            name='unlock_requirements',
            field=models.ManyToManyField(blank=True, related_name='spm_items', to='poryphone.ItemQuantity'),
        ),
        migrations.CreateModel(
            name='SyncPairPassive',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('passive', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='spp_passive', to='poryphone.Passive')),
                ('syncpair', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='spp_syncpair', to='poryphone.SyncPair')),
                ('unlock_requirements', models.ManyToManyField(blank=True, related_name='spp_items', to='poryphone.ItemQuantity')),
            ],
        ),
        migrations.CreateModel(
            name='SyncMove',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255, unique=True)),
                ('power', django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(), blank=True, null=True, size=2)),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='poryphone.Category')),
                ('syncpair', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sm_syncpair', to='poryphone.SyncPair')),
                ('target', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='poryphone.Target')),
                ('type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='poryphone.Type')),
            ],
        ),
    ]
