# Generated by Django 2.2.4 on 2020-02-07 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('poryphone', '0044_auto_20200207_0905'),
    ]

    operations = [
        migrations.AddField(
            model_name='syncmove',
            name='description',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
