# Generated by Django 2.2.4 on 2020-02-09 01:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('poryphone', '0046_auto_20200208_2025'),
    ]

    operations = [
        migrations.AlterField(
            model_name='itemquantity',
            name='item',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='iqs', to='poryphone.Item'),
        ),
        migrations.AlterField(
            model_name='syncmove',
            name='syncpair',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='syncmoves', to='poryphone.SyncPair'),
        ),
        migrations.AlterField(
            model_name='syncpair',
            name='trainer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='syncpair', to='poryphone.Trainer'),
        ),
        migrations.AlterField(
            model_name='syncpairmove',
            name='unlock_requirements',
            field=models.ManyToManyField(blank=True, related_name='spmoves', to='poryphone.ItemQuantity'),
        ),
        migrations.AlterField(
            model_name='syncpairpassive',
            name='passive',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sppassive', to='poryphone.Passive'),
        ),
        migrations.AlterField(
            model_name='syncpairpassive',
            name='syncpair',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sppassive', to='poryphone.SyncPair'),
        ),
        migrations.AlterField(
            model_name='syncpairpassive',
            name='unlock_requirements',
            field=models.ManyToManyField(blank=True, related_name='sppassive', to='poryphone.ItemQuantity'),
        ),
    ]
