# Generated by Django 2.2.13 on 2020-06-12 19:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('poryphone', '0047_auto_20200208_2029'),
    ]

    operations = [
        migrations.AddField(
            model_name='pokemon',
            name='img',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='trainer',
            name='img',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
