# Generated by Django 2.2.13 on 2020-06-17 19:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('poryphone', '0050_auto_20200616_1450'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pokemon',
            old_name='img',
            new_name='img_path',
        ),
    ]
