# Generated by Django 2.2.13 on 2020-06-18 00:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('poryphone', '0051_auto_20200617_1533'),
    ]

    operations = [
        migrations.RenameField(
            model_name='trainer',
            old_name='img',
            new_name='img_path',
        ),
    ]
